
import { StyleSheet } from 'react-native';


const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f8f8f8',
    },
    header: {
      height: 200,
      overflow: 'hidden',
    },
    headerBackground: {
      height: '100%',
      width: '100%',
    },
    headerGradient: {
      height: '100%',
      width: '100%',
      justifyContent: 'space-between',
    },
    headerTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 40,
    },
    menuButton: {
      padding: 5,
    },
    logoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    appName: {
      fontSize: 24,
      fontWeight: 'bold',
      color: 'white',
      marginLeft: 8,
    },
    headerIcons: {
      flexDirection: 'row',
    },
    iconButton: {
      marginLeft: 16,
    },
    headerContent: {
      padding: 40,
    },
    welcomeText: {
      fontSize: 20,
      fontWeight: '500',
      color: 'white',
      opacity: 0.9,
    },
    tagline: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.8)',
      marginTop: 4,
    },
    dateText: {
      fontSize: 14,
      color: 'white',
      opacity: 0.9,
      marginTop: 5,
    },
    tipCard: {
      flexDirection: 'row',
      backgroundColor: 'white',
      borderRadius: 12,
      padding: 15,
      margin: 15,
      marginTop: -25,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    tipIconContainer: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: '#e8f5e9',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    tipContent: {
      flex: 1,
    },
    tipTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#333',
      marginBottom: 5,
    },
    tipText: {
      fontSize: 14,
      color: '#666',
      lineHeight: 20,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 15,
      color: '#2E7D32',
    },
    conditionsContainer: {
      padding: 20,
      backgroundColor: 'white',
      margin: 15,
      borderRadius: 12,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    conditionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    conditionCard: {
      width: '48%',
      borderRadius: 12,
      marginBottom: 15,
      overflow: 'hidden',
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
    },
    conditionGradient: {
      padding: 15,
      borderRadius: 12,
      position: 'relative',
      overflow: 'hidden',
    },
    conditionIcon: {
      marginBottom: 8,
    },
    conditionName: {
      fontSize: 14,
      color: '#666',
    },
    conditionValue: {
      fontSize: 22,
      fontWeight: 'bold',
      marginTop: 5,
    },
    statusIndicator: {
      position: 'absolute',
      top: 0,
      right: 0,
      width: 8,
      height: '100%',
    },
    alertsContainer: {
      padding: 20,
      backgroundColor: 'white',
      margin: 15,
      borderRadius: 12,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    alertCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f9f9f9',
      borderRadius: 12,
      padding: 12,
      marginBottom: 15,
      elevation: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 1,
    },
    alertPlantImage: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginRight: 10,
    },
    alertIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    alertContent: {
      flex: 1,
    },
    alertPlantName: {
      fontWeight: 'bold',
      fontSize: 16,
      color: '#333',
    },
    alertMessage: {
      color: '#666',
      fontSize: 14,
      marginBottom: 5,
    },
    alertProgressContainer: {
      height: 4,
      backgroundColor: '#e0e0e0',
      borderRadius: 2,
      width: '100%',
    },
    alertProgress: {
      height: 4,
      borderRadius: 2,
    },
    alertActionButton: {
      backgroundColor: '#4CAF50',
      paddingVertical: 6,
      paddingHorizontal: 14,
      borderRadius: 20,
      elevation: 1,
    },
    alertActionText: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 12,
    },
  
      navigationButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 15,
        marginBottom: 15,
        },
        navButton: {
        flex: 0.48,
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        },
        navButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 16,
        borderRadius: 12,
        },
        navButtonText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
        marginLeft: 8,
        },
        communityContainer: {
        padding: 20,
        backgroundColor: 'white',
        margin: 15,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        },
        communitySubtitle: {
        fontSize: 14,
        color: '#666',
        marginBottom: 15,
        marginTop: -10,
        },
        communityScroll: {
        marginHorizontal: -5,
        },
        communityCard: {
        width: 160,
        backgroundColor: '#f9f9f9',
        borderRadius: 12,
        overflow: 'hidden',
        marginHorizontal: 5,
        elevation: 1,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
        },
        communityImage: {
        width: '100%',
        height: 100,
        },
        communityCardTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#333',
        padding: 10,
        paddingBottom: 2,
        },
        communityCardMembers: {
        fontSize: 12,
        color: '#666',
        paddingHorizontal: 10,
        paddingBottom: 10,
        },
        modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        },
        sideMenu: {
        width: '75%',
        height: '100%',
        backgroundColor: 'white',
        paddingTop: 50,
        paddingHorizontal: 20,
        },
        closeButton: {
        position: 'absolute',
        top: 15,
        right: 15,
        zIndex: 10,
        },
        userSection: {
        alignItems: 'center',
        marginBottom: 30,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        },
        userAvatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 10,
        },
        userName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
        },
        userEmail: {
        fontSize: 14,
        color: '#666',
        },
        menuItems: {
        marginBottom: 30,
        },
        menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        },
        menuItemText: {
        fontSize: 16,
        color: '#333',
        marginLeft: 15,
        },
        logoutButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        marginTop: 'auto',
        marginBottom: 30,
        },
        logoutText: {
        fontSize: 16,
        color: '#F44336',
        marginLeft: 15,
        fontWeight: 'bold',
        },
        });

export default styles;
       